<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forum_kaskus-next-header-logo</name>
   <tag></tag>
   <elementGuidId>4da7d613-408b-4f33-833e-360d44060b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kaskus-next-header-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='kaskus-next-header-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd337f98-7a23-4429-a0f6-80f69462cf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Peringatan Ulang Tahun ke-78 Republik Indonesia</value>
      <webElementGuid>04eae4e6-194a-4aa6-874c-b373ab7dfa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative mr-2 flex-shrink-0</value>
      <webElementGuid>bccaa7ac-5fb1-415b-84b8-617e964cff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kaskus-next-header-logo</value>
      <webElementGuid>07c6a254-112f-4a01-adcc-96f797d43083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kaskus.co.id</value>
      <webElementGuid>4ff1e730-6f86-47bc-a9c5-a0aeceedf380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kaskus-next-header-logo&quot;)</value>
      <webElementGuid>39710bf0-8492-46f2-8fbc-0d416d1ec872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='kaskus-next-header-logo']</value>
      <webElementGuid>f814b6ab-8764-4d3c-ad42-3bd4637bed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/a</value>
      <webElementGuid>fe1b0f75-f090-43f0-b760-8eb48f6aac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forum'])[1]/preceding::a[1]</value>
      <webElementGuid>ac3a90db-926c-4a5b-864d-490b74d8a3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Thread'])[1]/preceding::a[2]</value>
      <webElementGuid>e8bd87c8-037e-4dd7-8b02-9d2a1488b6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.kaskus.co.id')]</value>
      <webElementGuid>58b81f7c-fa48-4ad4-8b61-e9220859f2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>05ebc0e2-cd02-45f0-8b47-237cfb4e4068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Peringatan Ulang Tahun ke-78 Republik Indonesia' and @id = 'kaskus-next-header-logo' and @href = 'https://www.kaskus.co.id']</value>
      <webElementGuid>8518f4e9-ca8e-4c71-9dc8-0b8172a5922c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
